// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod pls {
        pub mod bitcoin {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod multisig {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type Buffer = _rt::Vec<u8>;
                pub type Address = _rt::String;
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum Network {
                    Signet,
                    Bitcoin,
                    Regtest,
                    Testnet,
                    Testnet4,
                }
                impl ::core::fmt::Debug for Network {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            Network::Signet => f.debug_tuple("Network::Signet").finish(),
                            Network::Bitcoin => {
                                f.debug_tuple("Network::Bitcoin").finish()
                            }
                            Network::Regtest => {
                                f.debug_tuple("Network::Regtest").finish()
                            }
                            Network::Testnet => {
                                f.debug_tuple("Network::Testnet").finish()
                            }
                            Network::Testnet4 => {
                                f.debug_tuple("Network::Testnet4").finish()
                            }
                        }
                    }
                }
                impl Network {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> Network {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => Network::Signet,
                            1 => Network::Bitcoin,
                            2 => Network::Regtest,
                            3 => Network::Testnet,
                            4 => Network::Testnet4,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                #[derive(Clone)]
                pub struct Options {
                    pub parts: _rt::Vec<Buffer>,
                    pub arbitrators: _rt::Vec<Buffer>,
                    pub quorum: u32,
                    pub internal_pubkey: Buffer,
                    pub network: Network,
                }
                impl ::core::fmt::Debug for Options {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Options")
                            .field("parts", &self.parts)
                            .field("arbitrators", &self.arbitrators)
                            .field("quorum", &self.quorum)
                            .field("internal-pubkey", &self.internal_pubkey)
                            .field("network", &self.network)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct Script {
                    pub combination: _rt::Vec<Buffer>,
                    pub leaf: Buffer,
                    pub weight: u32,
                }
                impl ::core::fmt::Debug for Script {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Script")
                            .field("combination", &self.combination)
                            .field("leaf", &self.leaf)
                            .field("weight", &self.weight)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct Utxo {
                    pub txid: Buffer,
                    pub vout: u32,
                    pub value: u64,
                }
                impl ::core::fmt::Debug for Utxo {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Utxo")
                            .field("txid", &self.txid)
                            .field("vout", &self.vout)
                            .field("value", &self.value)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct Txout {
                    pub value: u64,
                    pub address: Address,
                }
                impl ::core::fmt::Debug for Txout {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Txout")
                            .field("value", &self.value)
                            .field("address", &self.address)
                            .finish()
                    }
                }
                #[derive(Clone)]
                pub struct StartTxSpendingParams {
                    pub redeem_script: Buffer,
                    pub utxos: _rt::Vec<Utxo>,
                    pub outs: _rt::Vec<Txout>,
                }
                impl ::core::fmt::Debug for StartTxSpendingParams {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("StartTxSpendingParams")
                            .field("redeem-script", &self.redeem_script)
                            .field("utxos", &self.utxos)
                            .field("outs", &self.outs)
                            .finish()
                    }
                }
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct Multisig {
                    handle: _rt::Resource<Multisig>,
                }
                type _MultisigRep<T> = Option<T>;
                impl Multisig {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `Multisig`.
                    pub fn new<T: GuestMultisig>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _MultisigRep<T> = Some(val);
                        let ptr: *mut _MultisigRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestMultisig>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestMultisig>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestMultisig>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: u32) -> Self {
                        Self {
                            handle: unsafe { _rt::Resource::from_handle(handle) },
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> u32 {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> u32 {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = unsafe {
                            _rt::Box::from_raw(handle as *mut _MultisigRep<T>)
                        };
                    }
                    fn as_ptr<T: GuestMultisig>(&self) -> *mut _MultisigRep<T> {
                        Multisig::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`Multisig`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct MultisigBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a Multisig>,
                }
                impl<'a> MultisigBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestMultisig>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(&self) -> *mut _MultisigRep<T> {
                        Multisig::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for Multisig {
                    #[inline]
                    unsafe fn drop(_handle: u32) {
                        #[cfg(not(target_arch = "wasm32"))]
                        unreachable!();
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]pls:bitcoin/multisig@0.1.2"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-drop]multisig"]
                                fn drop(_: u32);
                            }
                            unsafe { drop(_handle) };
                        }
                    }
                }
                #[derive(Clone)]
                pub enum Error {
                    Parts(_rt::String),
                    Arbitrators(_rt::String),
                    InternalPubkey(_rt::String),
                }
                impl ::core::fmt::Debug for Error {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            Error::Parts(e) => {
                                f.debug_tuple("Error::Parts").field(e).finish()
                            }
                            Error::Arbitrators(e) => {
                                f.debug_tuple("Error::Arbitrators").field(e).finish()
                            }
                            Error::InternalPubkey(e) => {
                                f.debug_tuple("Error::InternalPubkey").field(e).finish()
                            }
                        }
                    }
                }
                impl ::core::fmt::Display for Error {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        write!(f, "{:?}", self)
                    }
                }
                impl std::error::Error for Error {}
                #[derive(Clone)]
                pub enum StartTxSpendingError {
                    Utxo(_rt::String),
                    Out(_rt::String),
                }
                impl ::core::fmt::Debug for StartTxSpendingError {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            StartTxSpendingError::Utxo(e) => {
                                f.debug_tuple("StartTxSpendingError::Utxo")
                                    .field(e)
                                    .finish()
                            }
                            StartTxSpendingError::Out(e) => {
                                f.debug_tuple("StartTxSpendingError::Out").field(e).finish()
                            }
                        }
                    }
                }
                impl ::core::fmt::Display for StartTxSpendingError {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        write!(f, "{:?}", self)
                    }
                }
                impl std::error::Error for StartTxSpendingError {}
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_multisig_address_cabi<T: GuestMultisig>(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::address(
                        unsafe { MultisigBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0.into_bytes()).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_multisig_address<T: GuestMultisig>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_multisig_internal_key_cabi<
                    T: GuestMultisig,
                >(arg0: *mut u8) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::internal_key(
                        unsafe { MultisigBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_multisig_internal_key<
                    T: GuestMultisig,
                >(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_multisig_scripts_cabi<T: GuestMultisig>(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::scripts(
                        unsafe { MultisigBorrow::lift(arg0 as u32 as usize) }.get(),
                    );
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec6 = result0;
                    let len6 = vec6.len();
                    let layout6 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec6.len() * (5 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result6 = if layout6.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout6).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout6);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec6.into_iter().enumerate() {
                        let base = result6
                            .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                        {
                            let Script {
                                combination: combination2,
                                leaf: leaf2,
                                weight: weight2,
                            } = e;
                            let vec4 = combination2;
                            let len4 = vec4.len();
                            let layout4 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec4.len() * (2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result4 = if layout4.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout4).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout4);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec4.into_iter().enumerate() {
                                let base = result4
                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let vec3 = (e).into_boxed_slice();
                                    let ptr3 = vec3.as_ptr().cast::<u8>();
                                    let len3 = vec3.len();
                                    ::core::mem::forget(vec3);
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len3;
                                    *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                                }
                            }
                            *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *base.add(0).cast::<*mut u8>() = result4;
                            let vec5 = (leaf2).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len5;
                            *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr5.cast_mut();
                            *base
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(weight2);
                        }
                    }
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                    *ptr1.add(0).cast::<*mut u8>() = result6;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_multisig_scripts<T: GuestMultisig>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base11 = l0;
                    let len11 = l1;
                    for i in 0..len11 {
                        let base = base11
                            .add(i * (5 * ::core::mem::size_of::<*const u8>()));
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base7 = l2;
                            let len7 = l3;
                            for i in 0..len7 {
                                let base = base7
                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l4 = *base.add(0).cast::<*mut u8>();
                                    let l5 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let base6 = l4;
                                    let len6 = l5;
                                    _rt::cabi_dealloc(base6, len6 * 1, 1);
                                }
                            }
                            _rt::cabi_dealloc(
                                base7,
                                len7 * (2 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let l8 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l9 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base10 = l8;
                            let len10 = l9;
                            _rt::cabi_dealloc(base10, len10 * 1, 1);
                        }
                    }
                    _rt::cabi_dealloc(
                        base11,
                        len11 * (5 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_multisig_start_tx_spending_cabi<
                    T: GuestMultisig,
                >(
                    arg0: *mut u8,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: *mut u8,
                    arg4: usize,
                    arg5: *mut u8,
                    arg6: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let base6 = arg3;
                    let len6 = arg4;
                    let mut result6 = _rt::Vec::with_capacity(len6);
                    for i in 0..len6 {
                        let base = base6
                            .add(i * (16 + 2 * ::core::mem::size_of::<*const u8>()));
                        let e6 = {
                            let l1 = *base.add(0).cast::<*mut u8>();
                            let l2 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len3 = l2;
                            let l4 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>();
                            let l5 = *base
                                .add(8 + 2 * ::core::mem::size_of::<*const u8>())
                                .cast::<i64>();
                            Utxo {
                                txid: _rt::Vec::from_raw_parts(l1.cast(), len3, len3),
                                vout: l4 as u32,
                                value: l5 as u64,
                            }
                        };
                        result6.push(e6);
                    }
                    _rt::cabi_dealloc(
                        base6,
                        len6 * (16 + 2 * ::core::mem::size_of::<*const u8>()),
                        8,
                    );
                    let base11 = arg5;
                    let len11 = arg6;
                    let mut result11 = _rt::Vec::with_capacity(len11);
                    for i in 0..len11 {
                        let base = base11
                            .add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
                        let e11 = {
                            let l7 = *base.add(0).cast::<i64>();
                            let l8 = *base.add(8).cast::<*mut u8>();
                            let l9 = *base
                                .add(8 + 1 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len10 = l9;
                            let bytes10 = _rt::Vec::from_raw_parts(
                                l8.cast(),
                                len10,
                                len10,
                            );
                            Txout {
                                value: l7 as u64,
                                address: _rt::string_lift(bytes10),
                            }
                        };
                        result11.push(e11);
                    }
                    _rt::cabi_dealloc(
                        base11,
                        len11 * (8 + 2 * ::core::mem::size_of::<*const u8>()),
                        8,
                    );
                    let result12 = T::start_tx_spending(
                        unsafe { MultisigBorrow::lift(arg0 as u32 as usize) }.get(),
                        StartTxSpendingParams {
                            redeem_script: _rt::Vec::from_raw_parts(
                                arg1.cast(),
                                len0,
                                len0,
                            ),
                            utxos: result6,
                            outs: result11,
                        },
                    );
                    let ptr13 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result12 {
                        Ok(e) => {
                            *ptr13.add(0).cast::<u8>() = (0i32) as u8;
                            let vec14 = (e).into_boxed_slice();
                            let ptr14 = vec14.as_ptr().cast::<u8>();
                            let len14 = vec14.len();
                            ::core::mem::forget(vec14);
                            *ptr13
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len14;
                            *ptr13
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr14.cast_mut();
                        }
                        Err(e) => {
                            *ptr13.add(0).cast::<u8>() = (1i32) as u8;
                            match e {
                                StartTxSpendingError::Utxo(e) => {
                                    *ptr13
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                    let vec15 = (e.into_bytes()).into_boxed_slice();
                                    let ptr15 = vec15.as_ptr().cast::<u8>();
                                    let len15 = vec15.len();
                                    ::core::mem::forget(vec15);
                                    *ptr13
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len15;
                                    *ptr13
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr15.cast_mut();
                                }
                                StartTxSpendingError::Out(e) => {
                                    *ptr13
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec16 = (e.into_bytes()).into_boxed_slice();
                                    let ptr16 = vec16.as_ptr().cast::<u8>();
                                    let len16 = vec16.len();
                                    ::core::mem::forget(vec16);
                                    *ptr13
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len16;
                                    *ptr13
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr16.cast_mut();
                                }
                            }
                        }
                    };
                    ptr13
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_method_multisig_start_tx_spending<
                    T: GuestMultisig,
                >(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                        _ => {
                            let l4 = i32::from(
                                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                            );
                            match l4 {
                                0 => {
                                    let l5 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l6 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l5, l6, 1);
                                }
                                _ => {
                                    let l7 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l8 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l7, l8, 1);
                                }
                            }
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_new_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: i32,
                    arg5: *mut u8,
                    arg6: usize,
                    arg7: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let base3 = arg0;
                    let len3 = arg1;
                    let mut result3 = _rt::Vec::with_capacity(len3);
                    for i in 0..len3 {
                        let base = base3
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        let e3 = {
                            let l0 = *base.add(0).cast::<*mut u8>();
                            let l1 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len2 = l1;
                            _rt::Vec::from_raw_parts(l0.cast(), len2, len2)
                        };
                        result3.push(e3);
                    }
                    _rt::cabi_dealloc(
                        base3,
                        len3 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let base7 = arg2;
                    let len7 = arg3;
                    let mut result7 = _rt::Vec::with_capacity(len7);
                    for i in 0..len7 {
                        let base = base7
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        let e7 = {
                            let l4 = *base.add(0).cast::<*mut u8>();
                            let l5 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len6 = l5;
                            _rt::Vec::from_raw_parts(l4.cast(), len6, len6)
                        };
                        result7.push(e7);
                    }
                    _rt::cabi_dealloc(
                        base7,
                        len7 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let len8 = arg6;
                    let result9 = T::new(Options {
                        parts: result3,
                        arbitrators: result7,
                        quorum: arg4 as u32,
                        internal_pubkey: _rt::Vec::from_raw_parts(
                            arg5.cast(),
                            len8,
                            len8,
                        ),
                        network: Network::_lift(arg7 as u8),
                    });
                    let ptr10 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result9 {
                        Ok(e) => {
                            *ptr10.add(0).cast::<u8>() = (0i32) as u8;
                            *ptr10
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = (e).take_handle() as i32;
                        }
                        Err(e) => {
                            *ptr10.add(0).cast::<u8>() = (1i32) as u8;
                            match e {
                                Error::Parts(e) => {
                                    *ptr10
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (0i32) as u8;
                                    let vec11 = (e.into_bytes()).into_boxed_slice();
                                    let ptr11 = vec11.as_ptr().cast::<u8>();
                                    let len11 = vec11.len();
                                    ::core::mem::forget(vec11);
                                    *ptr10
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len11;
                                    *ptr10
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr11.cast_mut();
                                }
                                Error::Arbitrators(e) => {
                                    *ptr10
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (1i32) as u8;
                                    let vec12 = (e.into_bytes()).into_boxed_slice();
                                    let ptr12 = vec12.as_ptr().cast::<u8>();
                                    let len12 = vec12.len();
                                    ::core::mem::forget(vec12);
                                    *ptr10
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len12;
                                    *ptr10
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr12.cast_mut();
                                }
                                Error::InternalPubkey(e) => {
                                    *ptr10
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<u8>() = (2i32) as u8;
                                    let vec13 = (e.into_bytes()).into_boxed_slice();
                                    let ptr13 = vec13.as_ptr().cast::<u8>();
                                    let len13 = vec13.len();
                                    ::core::mem::forget(vec13);
                                    *ptr10
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len13;
                                    *ptr10
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr13.cast_mut();
                                }
                            }
                        }
                    };
                    ptr10
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_new<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = i32::from(
                                *arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>(),
                            );
                            match l1 {
                                0 => {
                                    let l2 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l3 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l2, l3, 1);
                                }
                                1 => {
                                    let l4 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l5 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l4, l5, 1);
                                }
                                _ => {
                                    let l6 = *arg0
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l7 = *arg0
                                        .add(3 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l6, l7, 1);
                                }
                            }
                        }
                    }
                }
                pub trait Guest {
                    type Multisig: GuestMultisig;
                    fn new(opts: Options) -> Result<Multisig, Error>;
                }
                pub trait GuestMultisig: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> u32
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = val;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]pls:bitcoin/multisig@0.1.2"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-new]multisig"]
                                fn new(_: *mut u8) -> u32;
                            }
                            unsafe { new(val) }
                        }
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: u32) -> *mut u8
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = handle;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]pls:bitcoin/multisig@0.1.2"
                            )]
                            unsafe extern "C" {
                                #[link_name = "[resource-rep]multisig"]
                                fn rep(_: u32) -> *mut u8;
                            }
                            unsafe { rep(handle) }
                        }
                    }
                    fn address(&self) -> Address;
                    fn internal_key(&self) -> Buffer;
                    fn scripts(&self) -> _rt::Vec<Script>;
                    fn start_tx_spending(
                        &self,
                        params: StartTxSpendingParams,
                    ) -> Result<Buffer, StartTxSpendingError>;
                }
                #[doc(hidden)]
                macro_rules! __export_pls_bitcoin_multisig_0_1_2_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "pls:bitcoin/multisig@0.1.2#[method]multisig.address")] unsafe
                        extern "C" fn export_method_multisig_address(arg0 : * mut u8,) ->
                        * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_multisig_address_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Multisig > (arg0) } } #[unsafe
                        (export_name =
                        "cabi_post_pls:bitcoin/multisig@0.1.2#[method]multisig.address")]
                        unsafe extern "C" fn _post_return_method_multisig_address(arg0 :
                        * mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_method_multisig_address::<<$ty as
                        $($path_to_types)*:: Guest >::Multisig > (arg0) } } #[unsafe
                        (export_name =
                        "pls:bitcoin/multisig@0.1.2#[method]multisig.internal-key")]
                        unsafe extern "C" fn export_method_multisig_internal_key(arg0 : *
                        mut u8,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_multisig_internal_key_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Multisig > (arg0) } } #[unsafe
                        (export_name =
                        "cabi_post_pls:bitcoin/multisig@0.1.2#[method]multisig.internal-key")]
                        unsafe extern "C" fn
                        _post_return_method_multisig_internal_key(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*::
                        __post_return_method_multisig_internal_key::<<$ty as
                        $($path_to_types)*:: Guest >::Multisig > (arg0) } } #[unsafe
                        (export_name =
                        "pls:bitcoin/multisig@0.1.2#[method]multisig.scripts")] unsafe
                        extern "C" fn export_method_multisig_scripts(arg0 : * mut u8,) ->
                        * mut u8 { unsafe { $($path_to_types)*::
                        _export_method_multisig_scripts_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Multisig > (arg0) } } #[unsafe
                        (export_name =
                        "cabi_post_pls:bitcoin/multisig@0.1.2#[method]multisig.scripts")]
                        unsafe extern "C" fn _post_return_method_multisig_scripts(arg0 :
                        * mut u8,) { unsafe { $($path_to_types)*::
                        __post_return_method_multisig_scripts::<<$ty as
                        $($path_to_types)*:: Guest >::Multisig > (arg0) } } #[unsafe
                        (export_name =
                        "pls:bitcoin/multisig@0.1.2#[method]multisig.start-tx-spending")]
                        unsafe extern "C" fn
                        export_method_multisig_start_tx_spending(arg0 : * mut u8, arg1 :
                        * mut u8, arg2 : usize, arg3 : * mut u8, arg4 : usize, arg5 : *
                        mut u8, arg6 : usize,) -> * mut u8 { unsafe {
                        $($path_to_types)*::
                        _export_method_multisig_start_tx_spending_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::Multisig > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6) } } #[unsafe (export_name =
                        "cabi_post_pls:bitcoin/multisig@0.1.2#[method]multisig.start-tx-spending")]
                        unsafe extern "C" fn
                        _post_return_method_multisig_start_tx_spending(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*::
                        __post_return_method_multisig_start_tx_spending::<<$ty as
                        $($path_to_types)*:: Guest >::Multisig > (arg0) } } #[unsafe
                        (export_name = "pls:bitcoin/multisig@0.1.2#new")] unsafe extern
                        "C" fn export_new(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8,
                        arg3 : usize, arg4 : i32, arg5 : * mut u8, arg6 : usize, arg7 :
                        i32,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_new_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4, arg5,
                        arg6, arg7) } } #[unsafe (export_name =
                        "cabi_post_pls:bitcoin/multisig@0.1.2#new")] unsafe extern "C" fn
                        _post_return_new(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_new::<$ty > (arg0) } } const _
                        : () = { #[doc(hidden)] #[unsafe (export_name =
                        "pls:bitcoin/multisig@0.1.2#[dtor]multisig")]
                        #[allow(non_snake_case)] unsafe extern "C" fn dtor(rep : * mut
                        u8) { unsafe { $($path_to_types)*:: Multisig::dtor::< <$ty as
                        $($path_to_types)*:: Guest >::Multisig > (rep) } } }; };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_pls_bitcoin_multisig_0_1_2_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 4 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 4
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::string::String;
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    u32::MAX => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub use alloc_crate::boxed::Box;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::alloc;
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_multisig_world_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::pls::bitcoin::multisig::__export_pls_bitcoin_multisig_0_1_2_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::pls::bitcoin::multisig);
    };
}
#[doc(inline)]
pub(crate) use __export_multisig_world_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:pls:bitcoin@0.1.2:multisig-world:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 880] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xeb\x05\x01A\x02\x01\
A\x02\x01B'\x01p}\x04\0\x06buffer\x03\0\0\x01s\x04\0\x07address\x03\0\x02\x01m\x05\
\x06signet\x07bitcoin\x07regtest\x07testnet\x08testnet4\x04\0\x07network\x03\0\x04\
\x01p\x01\x01r\x05\x05parts\x06\x0barbitrators\x06\x06quorumy\x0finternal-pubkey\
\x01\x07network\x05\x04\0\x07options\x03\0\x07\x01r\x03\x0bcombination\x06\x04le\
af\x01\x06weighty\x04\0\x06script\x03\0\x09\x01r\x03\x04txid\x01\x04vouty\x05val\
uew\x04\0\x04utxo\x03\0\x0b\x01r\x02\x05valuew\x07address\x03\x04\0\x05txout\x03\
\0\x0d\x01p\x0c\x01p\x0e\x01r\x03\x0dredeem-script\x01\x05utxos\x0f\x04outs\x10\x04\
\0\x18start-tx-spending-params\x03\0\x11\x04\0\x08multisig\x03\x01\x01q\x03\x05p\
arts\x01s\0\x0barbitrators\x01s\0\x0finternal-pubkey\x01s\0\x04\0\x05error\x03\0\
\x14\x01q\x02\x04utxo\x01s\0\x03out\x01s\0\x04\0\x17start-tx-spending-error\x03\0\
\x16\x01h\x13\x01@\x01\x04self\x18\0\x03\x04\0\x18[method]multisig.address\x01\x19\
\x01@\x01\x04self\x18\0\x01\x04\0\x1d[method]multisig.internal-key\x01\x1a\x01p\x0a\
\x01@\x01\x04self\x18\0\x1b\x04\0\x18[method]multisig.scripts\x01\x1c\x01j\x01\x01\
\x01\x17\x01@\x02\x04self\x18\x06params\x12\0\x1d\x04\0\"[method]multisig.start-\
tx-spending\x01\x1e\x01i\x13\x01j\x01\x1f\x01\x15\x01@\x01\x04opts\x08\0\x20\x04\
\0\x03new\x01!\x04\0\x1apls:bitcoin/multisig@0.1.2\x05\0\x04\0\x20pls:bitcoin/mu\
ltisig-world@0.1.2\x04\0\x0b\x14\x01\0\x0emultisig-world\x03\0\0\0G\x09producers\
\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41\
.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
