name: Publish

on:
  release:
    types: [published]

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: https://registry.npmjs.org
          package-manager-cache: false

      - name: Cargo cache files
        uses: actions/cache@v6
        with:
          path: |
            .cargo-ci
          key: cargo-${{ hashFiles('Cargo.lock', 'Cargo.toml') }}
          restore-keys: |
            cargo-

      - name: Build and test in Devcontainers
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            set -e

            export CARGO_HOME="${PWD}/.cargo-ci"

            mkdir -p "${CARGO_HOME}"

            npm run build:ts

            nigiri start

            cd ts

            npm test -- --run

            cd -

      - name: Show package contents
        working-directory: ts
        run: |
          npm pack --dry-run

      - name: Publish to npm
        working-directory: ts
        run: |
          npm publish
